config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Dashboard
  get "profile", to: "dashboards#profile"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :flights do
    resources :bookings, only: %I[index show new create] do
      member do
        patch :accept
        patch :decline
      end
    end
  end
  resources :bookings, only: %I[destroy]
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flight
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :bookings, dependent: :destroy
  validates :capacity, :departure, :arrival, :date, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
  geocoded_by :arrival
  after_validation :geocode, if: :will_save_change_to_arrival?

  include PgSearch::Model
  pg_search_scope :search_by_departure_and_arrival,
                  against: %i[departure arrival],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :flights
  has_many :bookings
  has_one_attached :photo

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization # Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name pilot photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name pilot photo])
  end

  # Pundit
  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_flight, only: %i[index show create new]

  def index
    @bookings = @flight.bookings
  end

  def new
    @booking = Booking.new
    authorize @booking
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @flight = Flight.find(params[:flight_id])
    @booking.user = current_user
    @booking.flight = @flight
    authorize @booking

    if @booking.save
      # diminuer la capacité du flight concerné
      @flight.capacity -= 1
      @flight.save
      redirect_to profile_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.flight.capacity += 1 unless @booking.status == "false"
    @booking.destroy
    redirect_to profile_path, status: :see_other
  end

  def accept
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.status = "true"
    @booking.update(booking_params)
    redirect_to profile_path
  end

  def decline
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.flight.capacity += 1
    @booking.status = "false"
    @booking.update(booking_params)
    redirect_to profile_path
  end

  private

  def set_flight
    @flight = Flight.find(params[:flight_id])
  end

  def booking_params
    params.permit(:flight_id, :status)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def profile
    @user_flights = current_user.flights

    @user_bookings = current_user.bookings
    # Pundit
    authorize @user_flights
    authorize @user_bookings
  end

  def edit
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: %i[show edit update destroy]

  def index
    @flights = policy_scope(Flight)
    @booking = Booking.new
    if params[:query].present?
      @flights = Flight.search_by_departure_and_arrival(params[:query])
    else
      @flights = Flight.all
    end
    @markers = @flights.geocoded.map do |flight|
      {
        lat: flight.latitude,
        lng: flight.longitude,
        info_window: render_to_string(partial: "info_window", locals: {flight: flight})
      }
    end
  end

  def show
    @booking = Booking.new
    authorize @flight
    # checker si user a déjà book le flight
    @already_book = false
    @flight.bookings.each do |booking|
      @already_book = true if booking.user_id == current_user.id
    end
    @markers =
      {
        lat: @flight.latitude,
        lng: @flight.longitude,
        info_window: render_to_string(partial: "info_window", locals: { flight: @flight })
      }
  end

  def new
    @flight = Flight.new
    authorize @flight # Pundit
  end

  def create
    @flight = Flight.new(flight_params)
    @flight.user = current_user
    authorize @flight # Pundit
    @flight.save!
    redirect_to flight_path(@flight)
  end

  def edit; end

  def update
    @flight.update!(flight_params)
    redirect_to flight_path(@flight)
  end

  def destroy
    @flight.destroy!
    redirect_to flights_path, status: :see_other
  end

  private

  def flight_params
    params.require(:flight).permit(:capacity, :departure, :arrival, :date, :price, :photo)
  end

  def set_flight
    @flight = Flight.find(params[:id])
    authorize @flight
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h2><%= @flight.departure %>-<%= @flight.arrival %></h2>
<p>Date : <%= @flight.date %></p>
<p>Capacity : <%= @flight.capacity %></p>
<p>Captain : <%= @flight.user.first_name %> <%= @flight.user.last_name %></p>

<% @bookings.each do |booking| %>
<p><%= booking.id %></p>
<p><%= booking.user.first_name %> <%= booking.user.last_name %></p>
<% end %>

<%= link_to "Book this flight", new_flight_booking_path(@flight) %>

<%# <%= link_to "Book this flight",
  flight_bookings_path(@flight),
  data: {turbo_method: :new, turbo_confirm: "Are you sure?"},
  class: "btn btn-flat"
%>

app/views/bookings/new.html.erb
<div class="container pt-5">
  <%= simple_form_for [@flight, @booking] do |f| %>
    <%= f.submit class: "btn btn-flat mt-4" %>
  <% end %>
</div>

<%# <%= link_to "Book this flight",
  flight_bookings_path(@flight),
  data: {turbo_method: :new, turbo_confirm: "Are you sure?"},
  class: "btn btn-flat"
%>

app/views/dashboards/_bookings-profile.html.erb
  <div>
      <%= link_to "Add a Booking", flights_path, class: "btn btn-flat mb-4" %>
      <% if @user_bookings.count > 0%>
        <%@user_bookings.each do |b| %>
        <div class="card-product">
          <% if b.flight.photo.attached? %>
            <%= cl_image_tag b.flight.photo.key %>
          <% else %>
            <img src="https://images.unsplash.com/photo-1527605158555-853f200063e9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=671&q=80" />
          <% end %>
          <div class="card-product-infos" style="flex-grow:1">
            <h2><%=b.flight.departure %> > <%=b.flight.arrival %></h2>
              <p>Date: <%= b.flight.date %></p>
              <p>Capacity: <%= b.flight.capacity %> people</p>
              <p>Price: <%= b.flight.price %> euros</p>
              <% if b.status == "Pending" %>
                <span class="btn btn-warning mt-3">Status : <%= b.status %></span>
              <% elsif b.status == "true" %>
                <span class="btn btn-success mt-3">Status : Confirmed </span>
              <%elsif b.status == "false" %>
                <span class="btn btn-danger mt-3">Status : Rejected </span>
              <%end %>
          </div>
          <div class="card-product-infos">
              <%= link_to "Cancel booking", booking_path(b.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-outline-danger me-3" %>
          </div>
        </div>
        <br>
        <% end %>
      <% end %>
  </div>

app/views/dashboards/_pilot-profile.html.erb
  <div >
    <% if current_user.pilot == true%>
      <%= link_to "Add a Flight", new_flight_path, class: "btn btn-flat mb-4" %>
      <% @user_flights.each do |f| %>
      <div class="card-product">
        <% if f.photo.attached? %>
          <%= cl_image_tag f.photo.key %>
        <% else %>
          <img src="https://www.openfly.fr/contentfiles/content-page-pictures/14309/GE%CC%81NE%CC%81RAL-2.webp" />
        <% end %>
        <div class="card-product-infos" style="flex-grow: 1">
          <h2><%=f.departure %> > <%=f.arrival %></h2>
              <p>Date: <%=f.date %></p>
              <p>Capacity: <%=f.capacity %> people</p>
              <p>Price/p: <%=f.price %> euros</p>
        </div>
        <div class="card-product-infos">
          <%= link_to "Edit", edit_flight_path(f.id), class: "btn btn-outline-info me-3" %>
          <%= link_to "Cancel", flight_path(f.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-outline-danger me-3" %>
        </div>
      </div>

      <div class="d-flex flex-column">
        <% if f.bookings.size > 0 %>
          <% sum = 0 %>
            <% f.bookings.each do |b| %>
              <% unless b.status == "false" %>
              <div >
                <div class="card-booking-flight d-flex mt-1">
                  <div class="card-product-infos p-2">
                    <%= cl_image_tag b.user.photo.key, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle" %>
                  </div>
                  <div class="card-product-infos p-2">
                    <span><%= b.reload_user.first_name %> <%= b.reload_user.last_name %></span>
                    <span class="d-block"><%= b.reload_user.email %></span>
                    <h2>Seat <%= sum += 1 %></h2>
                  </div>
                  <div class="card-product-infos ms-4 p-2">
                    <%= link_to "Accept", accept_flight_booking_path(f,b), data: {turbo_method: :patch, turbo_confirm: "Are you sure?"}, class: "btn btn-outline-success m-1" unless b.status == "true"%>
                    <%= link_to "Decline", decline_flight_booking_path(f, b), data: {turbo_method: :patch, turbo_confirm: "Are you sure?"}, class: "btn btn-outline-danger m-1" %>
                  </div>
              </div>
              <%end %>
            <% end %>
        <% end %>
      </div>
      <br>
      <% end %>
    <% end %>
  </div>

app/views/dashboards/profile.html.erb
<div class="container pt-4">
  <h1>Hello, <%= current_user.first_name %> <%= current_user.last_name %> !</h1>

  <div class="card-profile">
    <div class="img-profile">
      <% if current_user.photo.key %>
        <%= cl_image_tag current_user.photo.key %>
      <% else %>
        <%= cl_image_tag("https://images.assetsdelivery.com/compings_v2/nexusby/nexusby1810/nexusby181000286.jpg") %>
      <% end %>
    </div>
    <div class="card-profile-infos">
      <p><strong>Name : </strong></p>
      <%= current_user.first_name %> <%= current_user.last_name %>
    </div>
    <div class="card-profile-infos">
      <p><strong>Email :</strong></p>
      <%= current_user.email %>
    </div>
    <div class="card-profile-infos">
      <p><strong>Pilot :</strong></p>
      <%= current_user.pilot ? "Yes 🛩 " : "No 🐣"%>
    </div>
      <div><%= link_to "Update profile", edit_user_registration_path, class: "btn btn-info m-2 mt-3 me-5" %></div>
  </div>

  <br>

  <%= render "pilot-profile" %>
  
  <br>
  <%= render "bookings-profile" %>
</div>

app/views/flights/_info_window.html.erb
<div class="card-trip" style="margin: -15px;">
    <% if flight.photo.attached? %>
      <%= cl_image_tag flight.photo.key, id: "modal-flight" %>
    <% else %>
      <img src="https://www.openfly.fr/contentfiles/content-page-pictures/14309/GE%CC%81NE%CC%81RAL-2.webp" id="modal-flight" />
    <% end %>
  <div class="card-trip-infos">
    <div>
      <h2><%= flight.departure %> - <%=flight.arrival %></h2>
      <p><%= flight.price %>€</p>
      <p>Date: <%= flight.date %></p>
      <p>Operated by <strong><%= flight.user.first_name %> <%= flight.user.last_name %></strong></p>
      <p>Total Capacity: <%= flight.capacity %></p>
    </div>
    <% if flight.user.photo.key %>
      <%= cl_image_tag flight.user.photo.key, crop: :thumb, gravity: :face, class: "card-trip-user avatar-bordered", id: "modal-avatar", style: "width: 40px !important; height: 40px !important; top: -20px !important; right: 10px" %>
    <% else %>
      <%= image_tag("https://images.assetsdelivery.com/compings_v2/nexusby/nexusby1810/nexusby181000286.jpg", class: "card-trip-user avatar-bordered", id: "modal-avatar", style: "width: 40px !important; height: 40px !important; top: -20px !important; right: 10px") %>
    <% end %>
  </div>
</div>

app/views/flights/_modal.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-flat me-4" data-bs-toggle="modal" data-bs-target="#flight<%=flight.id%>Modal">
  Book now
</button>

<!-- Modal -->
<div class="modal fade" id="flight<%=flight.id%>Modal" tabindex="-1" aria-labelledby="flight<%=flight.id%>ModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="flight<%=flight.id%>ModalLabel">Book flight</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="card-trip">
            <% if flight.photo.attached? %>
              <%= cl_image_tag flight.photo.key, id: "modal-flight" %>
            <% else %>
              <img src="https://www.openfly.fr/contentfiles/content-page-pictures/14309/GE%CC%81NE%CC%81RAL-2.webp" id="modal-flight" />
            <% end %>
          <div class="card-trip-infos">
            <div>
              <h2><%= flight.departure %> - <%=flight.arrival %> &emsp; &emsp; <%= flight.price %>€</h2>
              <p>Date: <%= flight.date %></p>
              <p>Operated by <strong><%= flight.user.first_name %> <%= flight.user.last_name %></strong></p>
              <p>Total Capacity: <%= flight.capacity %></p>
            </div>
            <% if flight.user.photo.key %>
              <%= cl_image_tag flight.user.photo.key, crop: :thumb, gravity: :face, class: "card-trip-user avatar-bordered", id: "modal-avatar" %>
            <% else %>
              <%= image_tag("https://images.assetsdelivery.com/compings_v2/nexusby/nexusby1810/nexusby181000286.jpg", class: "card-trip-user avatar-bordered", id: "modal-avatar") %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-flat bg-dark" data-bs-dismiss="modal">Close</button>
        <%= simple_form_for [flight, @booking] do |f| %>
          <%= f.submit class: "btn btn-flat", value: "Confirm", data: {turbo_confirm: "Are you sure?"} %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flights/edit.html.erb
<h1>Edit Flight</h1>
<div class="container">
  <%= simple_form_for [@flight] do |f| %>
    <%= f.input :capacity %>
    <%= f.input :date %>
    <%= f.input :departure %>
    <%= f.input :arrival %>
    <%= f.input :price %>
    <%= f.submit class: "btn btn-flat mt-4" %>
  <% end %>
</div>

app/views/flights/index.html.erb
<div class="container pt-3">
  <div class="container p-0">
    <%= link_to "Flying soon? Create a flight", new_flight_path, class: "btn btn-outline-primary" if current_user.pilot %>
  </div>
  <br>
  <%= simple_form_for :search, url: flights_path, method: :get do |f| %>
    <div class="search-form-control form-group mb-3">
      <%= text_field_tag :query,
          params[:query],
          class: "form-control string required rounded-pill bg-light bg-gradient",
          placeholder: "  Find a flight" %>
      <%= submit_tag "Search", class: "btn btn-flat rounded-pill me-1" %>
      </button>
    </div>
  <% end %>
    <div class="d-flex justify-content-center">
      <div style="width: 100%; height: 460px;"
      data-controller="big-map"
      data-big-map-markers-value="<%= @markers.to_json %>"
      data-big-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
  </div>
  <br>

    <% if @flights.empty? %>
      <p> 🛩 There's no flight soon for your search. Please try another one :-) </p>
    <% else %>
      <% @flights.each do |flight| %>
        <div class="card-product mt-4 mb-4">
          <% if flight.photo.attached? %>
            <%= cl_image_tag flight.photo.key %>
          <% else %>
            <img src="https://www.openfly.fr/contentfiles/content-page-pictures/14309/GE%CC%81NE%CC%81RAL-2.webp" />
          <% end %>

          <div class="card-product-infos" style="flex-grow: 1;">
            <h2><%= flight.departure %> > <%= flight.arrival%></h2>
            <p>Date: <strong><%= flight.date%></strong></p>
            <p>Price: <strong><%= flight.price%></strong></p>
            <% if flight.capacity < 1 %>
              <p><strong>No seat remaining</strong></p>
            </div>
              <div class="card-product-infos">
                <%= link_to "Full", flight_path(flight), class: "btn btn-flat disabled me-2", style: "position: right" %>
              </div>
            <% else %>
            <p>Capacity : <strong><%= flight.capacity %></strong></p>
          </div>
            <div class="card-product-infos">
              <%# <%= link_to "See details", flight_path(flight), class: "btn btn-flat", style: "position: right" %>
              <%= render "modal", flight: flight, style: "position: right" %>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
</div>

app/views/flights/new.html.erb
<div class="container pt-5">
<h3>Add your new flight :</h3>
  <%= simple_form_for [@flight] do |f| %>
    <%= f.input :capacity %>
    <%= f.input :date %>
    <%= f.input :departure,
                input_html: {data: {address_autocomplete_target: "arrival"}, class: "d-none"},
                wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}},
                label: "Departure airport" %>
    <%= f.input :arrival,
                input_html: {data: {address_autocomplete_target: "arrival"}, class: "d-none"},
                wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}},
                label: "Arrival airport"
    %>
    <%= f.input :photo, as: :file, label: "Plane or Flight picture" %>
    <%= f.input :price, label: "Price (per passenger)" %>
    <%= f.submit class: "btn btn-flat mt-4" %>
  <% end %>
</div>

app/views/flights/show.html.erb
<div class="container pt-3">
  <div>
    <%= link_to "◁ Back to flights", flights_path, class: "btn btn-outline-dark mt-3 mb-3" %>
  </div>

  <div class="card-trip">
      <% if @flight.photo.attached? %>
        <%= cl_image_tag @flight.photo.key %>
      <% else %>
        <img src="https://www.openfly.fr/contentfiles/content-page-pictures/14309/GE%CC%81NE%CC%81RAL-2.webp" />
      <% end %>
    <div class="card-trip-infos">
      <div>
        <h2><%= @flight.departure %> - <%=@flight.arrival %> &emsp; &emsp; <%= @flight.price %>€</h2>
        <p>Date: <%= @flight.date %></p>
        <p>Operated by <strong><%= @flight.user.first_name %> <%= @flight.user.last_name %></strong></p>
        <p>Total Capacity: <%= @flight.capacity %></p>
      </div>
      <%# <h2 class="card-trip-pricing"></h2> %>
      <div>
          <%= simple_form_for [@flight, @booking] do |f| %>
                <%= f.submit class: "btn btn-flat mt-4", value: "Book now", data: {turbo_confirm: "Are you sure?"} %>
            <% if policy(@flight).edit? && policy(@flight).destroy? %>
            <%= link_to "Edit", edit_flight_path(@flight), class: "btn btn-dark mt-4" %>
              <%= link_to "Delete", flight_path(@flight), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger mt-4 text-white" %>
            <% end %>
          <% end %>
      </div>
      <% if @flight.user.photo.key %>
        <%= cl_image_tag @flight.user.photo.key, crop: :thumb, gravity: :face, class: "card-trip-user avatar-bordered" %>
      <% else %>
        <%= image_tag("https://images.assetsdelivery.com/compings_v2/nexusby/nexusby1810/nexusby181000286.jpg", class: "card-trip-user avatar-bordered") %>
      <% end %>
    </div>
  </div>

  <% if current_user == @flight.user %>
  <div>
    <% unless @flight.bookings.empty? %>
    <div class="card-product mt-5 mb-2" style="height: 50px; justify-content:center; background-color: #670AFF; color: white;">
      <div class="card-product-infos">
        <h2>Passengers' list :</h2>
      </div>
    </div>
    <% end %>
    <% @flight.bookings.each do |booking| %>
      <div class="card-product mt-2 mb-2">
        <% if booking.user.photo.key %>
          <%= cl_image_tag booking.user.photo.key, height: 300, width: 400, crop: :fill %>
        <% else %>
          <%= image_tag("https://images.assetsdelivery.com/compings_v2/nexusby/nexusby1810/nexusby181000286.jpg") %>
        <% end %>

        <div class="card-product-infos" style="flex-grow: 1;">
          <h2><%= booking.user.first_name %> <%= booking.user.last_name %></h2>
          <p>Booking ID <strong>#<%= booking.id %></strong></p>
        </div>
        <div>
          <%= link_to "Cancel booking", booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-flat mt-4 me-4" %>
        </div>
      </div>
    <% end %>
  </div>
  <% end %>

  <div>
    <div class="card-product mt-5 mb-2" style="height: 50px; justify-content:center; background-color: #670AFF; color: white;">
          <div class="card-product-infos">
            <h2>Arrival map :</h2>
          </div>
    </div>

    <div class="d-flex justify-content-center">
      <div style="width: 100%; height: 460px;"
        data-controller="map"
        data-map-marker-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://www.freeiconspng.com/thumbs/airplane-icon-png/transport-airplane-takeoff-icon--android-iconset--icons8-2.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link ps-3 pe-3" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", profile_path, class: "nav-link ps-3 pe-3" %>
          </li>
          <li class="nav-item dropdown ps-3 pe-3">
                <% if current_user.photo.key %>
                  <%= cl_image_tag current_user.photo.key, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <% else %>
                  <%= image_tag("https://images.assetsdelivery.com/compings_v2/nexusby/nexusby1810/nexusby181000286.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
                <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Add a flight", new_flight_path, class: "dropdown-item" if current_user.pilot %>
              <%= link_to "Update profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/pages/_banner-home-antoine.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://media.cntraveler.com/photos/5e14ee62a59b790008c7f107/16:9/w_2560%2Cc_limit/Surf-Air-Pilatus_1.jpg);">
    <div class="container">
      <div class="banner-infos">
        <h1>Welcome to BlaBlaFlight !</h1>
        <p>Find your next private jet escape and travel around the world now</p>
        <%= link_to "Discover our flights now", flights_path, class: "btn btn-flat rounded-pill " %>
      </div>
      <%= simple_form_for :search, url: flights_path, method: :get do |f| %>
        <div class="search-form-control form-group mt-5 mb-3">
          <%= text_field_tag :query,
              params[:query],
              class: "form-control string required text-primary rounded-pill bg-light bg-gradient",
              placeholder: "  Find your next flight" %>
          <%= submit_tag "Search", class: "btn btn-flat rounded-pill" %>
        </div>
      <% end %>
    </div>
</div>